### Numpy 라이브러리

 - 고성능, 대용량 산술 연산을 위해서 사용하는 라이브러리
 - list와 비슷한, 산술연산이 가능한 배열(array) 자료구조를 제공
 - 배열을 사용한다면, 반복문 없이 대용량 산술 연산이 가능하다.

In [1]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [1]:
# 라이브러리, 모듈 불러오기
# import 불러올 라이브러리의 이름

import numpy as np
# as : 별칭
# 나는 numpy를 불러올 때, 앞으로 np라고 부를거야 라고 선언!!

### 배열 생성

In [3]:
# numpy에서 제공하는 배열 생성
# 1. 배열 생성에 기초가 되는 list 변수 생성-> array 생성
# 배열의 기초가 될 리스트 생성
list1 = [1,2,3,4,5]

In [4]:
# array 함수 불러오기
# numpy에 접근한 다음, array함수를 호출
# 1차원 배열 생성
np.array(list1)

array([1, 2, 3, 4, 5])

In [5]:
# 2차원 배열 생성
list2 = [[1,2,3],
         [4,5,6],
         [7,8,9]]

In [6]:
np.array(list2)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
# 2. list 변수 선언 없이 직접 매개변수로 전달 
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

### 배열의 정보 확인

In [21]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [28]:
arr2 = np.array([[1,2,3]
                ,[4,5,6]])

In [22]:
# 1. 배열의 모양을 확인 -> shape
# 해당 배열이 몇 차원의 배열인지 확인하는 함수
# 배열명.shape
# -> shape는 함수가 아니라 속성이기 때문에 소괄호를 작성하지 않는다
arr1.shape


# -> 결과값 : 튜플
# 튜플의 요소가 하나라면 1차원, 2개라면 2차원, 3개라면 3차원, 4개라면, 4차원
# (5,) -> 1차원인데, 요소는 5개있다!


(5,)

In [29]:
arr2.shape
# (2, 3) -> 2차원이고, 행이 2개, 열이 3개 있다!

(2, 3)

In [10]:
# 2. 배열의 차원 수를 확인 -> ndim
# ndim(number dimension) : 해당 배열의 차원 수를 확인하는 함수
# -> 반환값은 해당 배열의 차원 수를 반환


In [31]:
arr1.ndim
arr2.ndim

2

In [32]:
# 배열은 list와 다르게 단일 자료형으로만 구성
# 배열이 가지고 있는 요소들의 자료형을 조회

# 3. 배열 안에 있는 요소들의 데이터 타입 확인 -> dtype
arr3 = np.array([1.0, 2.0, 3.0])

In [33]:
arr3.dtype

dtype('float64')

In [34]:
# 4. 배열 안에 있는 모든 원소의 개수를 세어주는 속성 -> size
arr1.size

5

In [35]:
arr2.size

6

In [36]:
arr3.size

3

### 실습 예제

In [37]:
#배열의 크기, 차원, 젖ㄴ체 요소의 개수 확인
arr4 = np.array([[1,2,3,4]
                 ,[5,6,7,8]])

print("arr4의 모양: ", arr4.shape)
print("arr4의 차원의 수: ", arr4.ndim)
print("arr4의 원소 개수: ", arr4.size)
print("arr4의 자료형: ", arr4.dtype)

arr4의 모양:  (2, 4)
arr4의 차원의 수:  2
arr4의 원소 개수:  8
arr4의 자료형:  int64


### 임의의 숫자로 채워진 배열 생성

In [ ]:
# 배열을 임의의 모양만큼 만들어주는 함수

# 0으로 이루어진 배열 생성
# np.zeros(배열의 모양, dtype = 자료형)

arr5 = np.zeros((2,4), dtype = 'int')
arr5
# 초기값 생성(빈 데이터 공간 만들기)
# True / False 값을 숫자 0과 1로 표현
# 예를 들어 0으로 채워진 배열을 만들고 나중에 값을 하나씩 넣기
# 0으로 채워진 배열을 만들고(불합격) 합격인 데이터만 1로 바꾸기

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [42]:
# 1로 이루어진 배열 생성
# ones()
arr6 = np.ones((3,2), dtype = 'int')
arr6

array([[1, 1],
       [1, 1],
       [1, 1]])

In [45]:
# 0, 1 이외의 값으로 채워주고 싶을때
# full()
# -> 원하는 숫자를 원하는 형태로 만들어주는 함수
# np.full((배열의 형태), 넣고자 하는 자료형)
arr7 = np.full((5,), 2.0)
arr7

array([2., 2., 2., 2., 2.])

In [47]:
# 랜덤으로 값을 채워주는 함수
# random
# np.random.randint(시작값, 끝 값, 배열 모양 -> size = ())
# 끝 값은 포함하지 않는다 (슬라이싱과 같다)
arr8 = np.random.randint(1, 11, size = (2,2))
arr8

array([[5, 2],
       [8, 8]], dtype=int32)

In [57]:
# 1부터 50까지 들어있는 배열을 만들어보자.

# 1. 1부터 50까지 들어있는 리스트 생성
# 1-1. 빈 리스트 생성
list4 = []


# 1-2. 반복문과 range 사용
for i in range(1,51):
    list4.append(i)
print(list4)


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]


In [58]:
#2. 1번에서 만든 리스트를 배열로 변환
np.array(list4)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [61]:
# numpy에 원하는 숫자만큼 배열로 만들어주는 함수 존재
# arange
# arange(시작할 값, 끝 값, 증감량) -> 시작 값부터 끝 값의 전까지 이루어진 배열
arr5 = np.arange(1, 51)
arr5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [ ]:
# 배열을 생성할 때, 타입을 지정
# -> 배열 안에 있는 요소의 자료형을 일치시켜줄 수 있다.
# -> 배열은 각기 다른 자료형을 요소로 받아들일 수 없다.
arr6 = np.array([1,2,3], dtype= 'float')
arr6

array([1., 2., 3.])

In [64]:
# 생성할 때 잘못 만들었다면, astype 함수를 통해 자료형을 바꿔줄 수 있다.
# arr.astype('자료형')
arr7 = np.array(['1',2,3], dtype= 'float')
arr7

array([1., 2., 3.])

In [69]:
# astype은 원본 데이터에 영향을 미치지는 않는다 
# -> 따로 변수에 담아주거나, 같은 변수에 재정의 해주어야 사용 가능하다
# 다른 변수에 담기
arr7_int = arr7.astype('int')
arr7_int

array([1, 2, 3])

In [22]:
# 같은 변수에 재정의


### 배열 연산

In [3]:
# 배열의 산술연산 가능한 속성
list1 = [1,2,3]
list2 = [4,5,6]

list1 + list2

[1, 2, 3, 4, 5, 6]

In [5]:
# list1,2를 기반으로 배열로 만들어서 산술연산 하면 어떻게 되는가? 
arr1 = np.array(list1)
arr2 = np.array(list2)
print(arr1, arr2)

[1 2 3] [4 5 6]


In [6]:
arr1 + arr2
# 배열은 배열끼리 더하면 각 인덱스 번호에 맞는 요소끼리 연산된다.

array([5, 7, 9])

In [10]:
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)
print(arr1 % arr2)

[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 2 3]


In [14]:
# 비교 연산자
print(arr1 == arr2)
print(arr1 > arr2)
print(arr1 < arr2)

[False False False]
[False False False]
[ True  True  True]


In [16]:
# 배열과 정수랑 연산 O
# 리스트는 정수랑 연산 X
# 배열은 정수랑 연산이 가능하고, 각 요소별로 연산 후 array형태로 반환
arr1 * 2

array([2, 4, 6])

In [32]:
# 2차원 배열은 어떻게 연산이 되는지 확인
# 2차원 배열 -> 2,3
arr3 = np.array([[1,2,3]
                 ,[4,5,6]])
arr4 = arr3 * 3
print(arr3)
print(arr4)

[[1 2 3]
 [4 5 6]]
[[ 3  6  9]
 [12 15 18]]


In [33]:
arr3 + arr4

array([[ 4,  8, 12],
       [16, 20, 24]])

In [ ]:
# 배열끼리의 연산은, '배열 모양만 맞다면' 같은 인덱스 번호끼리 연산이 된다.
# 2차원 배열 -> 2,3
arr3 = np.array([[1,2,3]
                 ,[4,5,6]])

# 2차원 배열 -> 2, 4
arr4 = np.array([[7,8,9,10]
                 ,[11,12,13,14]])

print(arr3)
print(arr4)
print(arr3 + arr4)


[[1 2 3]
 [4 5 6]]
[[ 7  8  9 10]
 [11 12 13 14]]


ValueError: operands could not be broadcast together with shapes (2,3) (2,4) 